<a href="https://colab.research.google.com/github/renuka-singare/numpy/blob/main/NUMPY_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h4><b>NumPy Introduction</b></h4><br>
<h3><b>what is numpy?</b></h3>
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.


In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


**<h3>why we use numpy?</h3>**
<br>
In Python we have lists that serve the purpose of arrays, but they are slow to process.NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.



<h3>Import NumPy</h3>

In [ ]:
import numpy

<h3>creating numpy array</h3>

In [ ]:
import numpy as np
abc = np.array([1,2,3,4,5])
print([abc])
print(type(abc)) 

[array([1, 2, 3, 4, 5])]
<class 'numpy.ndarray'>


<h3>cheak version of numpy</h3>



In [ ]:
import numpy as np
print(np.__version__)

1.21.5


In [ ]:
import numpy as np
abc = np.array((1,2,3,4,5,6,7))
print(abc)

[1 2 3 4 5 6 7]


<h3>here i have created 0 D array</h3>

In [ ]:
import numpy as np
abc = np.array([34])
print(abc)

[34]


<h3>This one is 1 D array</h3>

In [ ]:
#1-d array
import numpy as np
abc = np.array([1, 2, 3, 4, 5])
print(abc)

[1 2 3 4 5]


<h3>This one is 2 D array</h3>

In [ ]:
import numpy as np
abc = np.array([[1,2],[3,4]])
print(abc)

[[1 2]
 [3 4]]


<h3>This one is 3 D array</h3>

In [ ]:
#3-d array
import numpy as np
abc = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(abc)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


<h3>here i have created all types of array simuntaniously</h3>

In [ ]:
import numpy as np
abc1 = np.array(34)
abc2 = np.array([1,2,3,4,5])
abc3 = np.array([[1,2],[3,4]])
abc4= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(abc1)
print(abc2)
print(abc3)
print(abc4)

34
[1 2 3 4 5]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


<h3>This one is higher dimention of array with the help of it we create all number of array as you want but the limit is 32 we can't be create greater than 32 dimention of array</h3>

In [ ]:
import numpy as np
abc = np.array([1,2,3,4,5,6], ndmin=6)
print(abc)
print('number of dimensions',abc.ndim) 

[[[[[[1 2 3 4 5 6]]]]]]
number of dimensions 6


<h2>Array indexing</h2>
<h3>with help of array indexing we can access our element fastly</h3>

In [ ]:
import numpy as np
abc = np.array([1,2,3,4,5])
print(abc[3])

4


In [ ]:
import numpy as np
abc =  np.array([1,2,3,4,5,6])
print(abc[3]+abc[4]) 

9


<h3>Array indexing fro 2d array</h3>


In [ ]:
import numpy as np
abc = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', abc[0, 1])

2nd element on 1st row:  2


In [ ]:
import numpy as np
abc = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element on 2nd row: ',abc[1,4])

5th element on 2nd row:  10


<h3>Array indexing for 3D array</h3>

In [ ]:
import numpy as np
abc = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(abc[0, 1, 2])

6


<h3>Array indexing for 2D array in reverse direction</h3>

In [ ]:
import numpy as np
abc = np.array ([[1,2,3,4,5],[6,7,8,9,10]])
print('last element from 2nd dim: ',abc[1,-1])

last element from 2nd dim:  10


<h2>Numpy slicing</h2>
<h3>Slicing in python means taking elements from one given index to another given index.
We pass slice instead of index like this: [start:end].
We can also define the step, like this: [start:end:step].
If we don't pass start its considered 0
If we don't pass end its considered length of array in that dimension
If we don't pass step its considered 1</h3>


In [ ]:
import numpy as np
abc = np. array([1,2,3,4,5,6,7,8])
print(abc[2:4]) 

[3 4]


In [ ]:
import numpy as np
abc = np. array([1,2,3,4,5,6,7,8])
print(abc[ :5]) 

[1 2 3 4 5]


In [ ]:
import numpy as np
abc = np. array([1,2,3,4,5,6,7,8])
print(abc[1:]) 

[2 3 4 5 6 7 8]


In [ ]:
import numpy as np
abc = np. array([1,2,3,4,5,6,7,8])
print(abc[-3:-1]) 

[6 7]


In [ ]:
import numpy as np
abc = np. array([1,2,3,4,5,6,7,8])
print(abc[1:2:4]) 

[2]


In [ ]:
import numpy as np
abc = np. array([1,2,3,4,5,6,7,8])
print(abc[ : :4]) 

[1 5]


In [ ]:
import numpy as np
abc = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(abc[1, 1:4])

[7 8 9]


###slicing for 2D array: 
####From both elements, return index 2:

In [ ]:
import numpy as np
abc = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(abc[0:2, 2])

[3 8]


####From both elements, slice index 1 to index 4 (not included), this will return a 2-D array

In [ ]:
import numpy as np
abc = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(abc[0:4, 1:4])

[[2 3 4]
 [7 8 9]]


###Data types in python
strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
integer - used to represent integer numbers. e.g. -1, -2, -3
float - used to represent real numbers. e.g. 1.2, 42.42
boolean - used to represent True or False.
complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j


In [ ]:
import numpy as np
abc = np.array([1,2,3,4,5,6])
print(abc.dtype) 

int64


In [ ]:
import numpy as np
abc = np.array(['apple','mango','banana','graps'])
print(abc.dtype) 

<U6


**For i, u, f, S and U we can define size as well.**

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype) 


[b'1' b'2' b'3' b'4']
|S1


In [ ]:
import numpy as np
abc = np.array([1, 2, 3, 4], dtype='S')
print(abc)
print(abc.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
import numpy as n
abc = np.array([1,2,3,4,5], dtype='i4')
print(abc)
print(abc.dtype)


[1 2 3 4 5]
int32


In [ ]:
import numpy as np
abc = np.array(['a','2','3'], dtype='U')
print(abc)
print(abc.dtype)

['a' '2' '3']
<U1


###**Converting Data Type on Existing Arrays**
####Change data type from float to integer by using 'i' as parameter value:

In [ ]:
import numpy as np
abc = np.array([1.2,2.4,3.4])
newabc = abc.astype('i')
print(newabc)
print(newabc.dtype)

[1 2 3]
int32


####Change data type from float to integer by using int as parameter value:

In [ ]:
import numpy as np
abc = np.array([1.2,2.3,3.4])
newabc = abc.astype('int')
print(newabc)
print(newabc.dtype)

[1 2 3]
int64


####Change data type from integer to boolean:

In [ ]:
import numpy as np
abc = np.array([1,0,3])
newabc = abc.astype(bool)
print(newabc)
print(newabc.dtype)

[ True False  True]
bool


##**The Difference Between Copy and View**
 #Make a copy, change the original array, and display both arrays:


In [ ]:
import numpy as np
abc = np.array([1,2,3,4,5])
X= abc.copy()
abc[4] = 42
print(abc)
print(abc.dtype)



[ 1  2  3  4 42]
int64


###Make a view, change the original array, and display both arrays:

In [ ]:
import numpy as np
abc = np.array([1,2,3,4,5,6])
x = abc.view()
abc[3] = 56
print(abc)
print(abc.dtype)


[ 1  2  3 56  5  6]
int64



###**Check if Array Owns it's Data** 
####Print the value of the base attribute to check if an array owns it's data or not:

In [ ]:
import numpy as np
abc = np.array([1,2,3,4,5])
x = abc.copy()
y = abc.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]
