<a href="https://colab.research.google.com/github/renuka-singare/numpy/blob/main/NUMPY_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy Shape**

In [ ]:
import numpy as np
abc = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(abc.shape)

(2, 4)


In [ ]:
import numpy as np
abc = np.array([1, 2, 3, 4], ndmin=5)
print(abc)
print('shape of array :', abc.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


**NumPy Array Reshaping**

In [ ]:
import numpy as np
abc = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newabc = abc.reshape(4, 3)
print(newabc)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**Reshape From 1-D to 3-D**

In [ ]:
import numpy as np
abc = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newabc = abc.reshape(2, 3, 2)
print(newabc)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
import numpy as np
abc = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(abc.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


**Unknown Dimension**

In [ ]:
import numpy as np
abc = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newabc = abc.reshape(2, 2, -1)
print(newabc)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Flattening the arrays**

In [ ]:
import numpy as np
abc = np.array([[1, 2, 3], [4, 5, 6]])
newabc = abc.reshape(-1)
print(newabc)

[1 2 3 4 5 6]


**NumPy Array Iterating**


In [ ]:
import numpy as np
abc = np.array([1, 2, 3])
for x in abc:
  print(x)

1
2
3


**Iterating 2-D Arrays**
####If we iterate on a n-D array it will go through n-1th dimension one by one.

In [ ]:
import numpy as np
abc = np.array([[1, 2, 3], [4, 5, 6]])
for x in abc:
  print(x)

[1 2 3]
[4 5 6]


####Iterate on each scalar element of the 2-D array:

In [ ]:
import numpy as np
abc= np.array([[1, 2, 3], [4, 5, 6]])
for x in abc:
  for y in x:
    print(y)

1
2
3
4
5
6


**Iterating 3-D Arrays**

In [ ]:
import numpy as np
abc = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in abc:
  print(x)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np
abc = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in abc:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


**Iterating Arrays Using nditer()**

In [ ]:
import numpy as np
abc = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(abc):
  print(x)

1
2
3
4
5
6
7
8


**Iterating Array With Different Data Types**

In [ ]:
import numpy as np
abc= np.array([1, 2, 3])
for x in np.nditer(abc, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


**Iterating With Different Step Size**

In [ ]:
import numpy as np
abc = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(abc[:, ::2]):
  print(x)

1
3
5
7


**Enumerated Iteration Using ndenumerate()**
####Enumerate on following 1D arrays elements:

In [ ]:
import numpy as np
abc = np.array([1, 2, 3])
for idx, x in np.ndenumerate(abc):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


####Enumerate on following 2D array's elements:

In [ ]:
import numpy as np
abc = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(abc):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


**Joining NumPy Arrays using concatinate function**

In [ ]:
import numpy as np
abc1 = np.array([1,2,3,4,5])
abc2 = np.array([3,4,5,6,7])
newabc = np.concatenate((abc1,abc2))
print(newabc)


[1 2 3 4 5 3 4 5 6 7]



**Joining Arrays Using Stack Functions**

In [ ]:
import numpy as np
abc1 = np.array([1,2,3,4,5])
abc2 = np.array([3,4,5,6,7])
newabc = np.stack((abc1,abc2),axis = 1)
print(newabc)

[[1 3]
 [2 4]
 [3 5]
 [4 6]
 [5 7]]


###**hstack**
####hstack is used for joining stack horizontally

In [ ]:
import numpy as np
abc1 = np.array([1,2,3,4,5])
abc2 = np.array([3,4,5,6,7])
newabc = np.hstack((abc1,abc2))
print(newabc)

[1 2 3 4 5 3 4 5 6 7]


###**vstack**
##### vstack is used for joining stack vertically

In [ ]:
import numpy as np
abc1 = np.array([1,2,3,4,5])
abc2 = np.array([3,4,5,6,7])
newabc = np.vstack((abc1,abc2))
print(newabc)


[[1 2 3 4 5]
 [3 4 5 6 7]]


###**dstack**
#####dstack is used for height, which is the same as depth.

In [ ]:
import numpy as np
abc1 = np.array([1,2,3,4,5])
abc2 = np.array([3,4,5,6,7])
newabc = np.dstack((abc1,abc2))
print(newabc)

[[[1 3]
  [2 4]
  [3 5]
  [4 6]
  [5 7]]]


**NumPy Splitting Array**

In [ ]:
import numpy as np
abc = np.array([1,2,3,4,5,6,7,8,9])
newabc = np.array_split(abc,3)
print(newabc)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


**If the array has less elements than required, it will adjust from the end accordingly.**

In [ ]:
import numpy as np
abc = np.array([1,2,3,4,5,6,7,8,9])
newabc = np.array_split(abc,5)
print(newabc)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9])]


**Split Into Arrays**

In [ ]:
import numpy as np
abc = np.array([1, 2, 3, 4, 5, 6])
newabc = np.array_split(abc, 3)
print(newabc[0])
print(newabc[1])
print(newabc[2])

[1 2]
[3 4]
[5 6]


In [ ]:
import numpy as np
abc = np.array([[1,2],[3,4],[4,5],[5,6],[2,3]])
newabc = np.array_split(abc, 3)
print(newabc)

[array([[1, 2],
       [3, 4]]), array([[4, 5],
       [5, 6]]), array([[2, 3]])]


In [ ]:
import numpy as np
abc = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newabc = np.array_split(abc, 3)
print(newabc)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


**use of axis**

In [ ]:
import numpy as np
abc = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newabc = np.split(abc, 3, axis=1)
print(newabc)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


**hsplit**

In [ ]:
import numpy as np
abc = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newabc = np.hsplit(abc, 3)
print(newabc)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


**vsplit**

In [ ]:
import numpy as np
abc = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newabc = np.vsplit(abc, 3)
print(newabc)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


**dsplit**

In [ ]:
import numpy as np
abc = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newabc = np.hsplit(abc, 3)
print(abc)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


###**Searching Arrays**
####Find the indexes where the value is 3:

In [ ]:
import numpy as np
abc = np.array ([1,2,3,4,5,6,7,3,5,3])
newabc = np.where(abc==3)
print(newabc)

(array([2, 7, 9]),)


####Find the indexes where the values are even:

In [ ]:
import numpy as np
abc=np.array([1,2,3,4,5,6,7,8])
newabc = np.where(abc%2==0)
print(newabc)

(array([1, 3, 5, 7]),)


####Find the indexes where the values are odd:

In [ ]:
import numpy as np
abc=np.array([1,2,3,4,5,6,7,8])
newabc = np.where(abc%2==1)
print(newabc)

(array([0, 2, 4, 6]),)


###**Search Sorted**
####Find the indexes where the value 7 should be inserted:

In [ ]:
import numpy as np
abc = np.array([1,2,3,4,5,6,7,8])
newabc = np.sort(abc)
print(newabc)

[1 2 3 4 5 6 7 8]


###**Search From the Right Side**

In [ ]:
import numpy as np
abc = np.array([6, 7, 8, 9])
x = np.searchsorted(abc, 7, side='right')
print(x)

2


####Find the indexes where the values 2, 4, and 6 should be inserted:

In [ ]:
import numpy as np
abc = np.array([1, 3, 5, 7])
x = np.searchsorted(abc, [2, 4, 6])
print(x)

[1 2 3]


###**NumPy Sorting Arrays**

####Sorting means putting elements in an ordered sequence.

In [ ]:
import numpy as np
abc = np.array([3, 2, 0, 1])
print(np.sort(abc))

[0 1 2 3]


In [ ]:
#Sort the array alphabetically:
import numpy as np
abc = np.array(['banana', 'cherry', 'apple'])
print(np.sort(abc))

['apple' 'banana' 'cherry']


In [ ]:
#Sort a boolean array:
import numpy as np
abc = np.array([True, False, True])
print(np.sort(abc))

[False  True  True]


In [ ]:
#sort 2-D array
import numpy as np
abc = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(abc))

[[2 3 4]
 [0 1 5]]


###**NumPy Filter Array**
#####Create an array from the elements on index 0 and 2:

In [ ]:
import numpy as np
abc = np.array([41, 42, 43, 44])
newabc = abc[[True, False, True, False]]
print(newabc)

[41 43]


####Create a filter array that will return only values higher than 42:

In [ ]:
import numpy as np
abc = np.array([41, 42, 43, 44])
filter_abc= []# Create an empty list
for element in abc:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_abc.append(True)
  else:
    filter_abc.append(False)
newabc = abc[filter_abc]
print(filter_abc)
print(newabc)

[False, False, True, True]
[43 44]


####Create a filter array that will return only even elements from the original array:

In [ ]:
import pandas as np
abc= np.array([41, 42, 43, 44])
filter_abc= []# Create an empty list
for element in abc:
  # if the element is higher than 42, set the value to True, otherwise False:
  if abc%2 == 0 :
    filter_abc.append(True)
  else:
    filter_abc.append(False)
newabc = abc[filter_abc]
print(filter_abc)
print(newabc)

[True, True, True, True]
<IntegerArray>
[41, 42, 43, 44]
Length: 4, dtype: Int64


**Creating Filter Directly From Array**

In [ ]:
import numpy as np
abc = np.array([41, 42, 43, 44])
filter_abc = abc > 42
newabc = abc[filter_abc]
print(filter_abc)
print(newabc)

[False False  True  True]
[43 44]


**Create a filter array that will return only even elements from the original array:**

In [ ]:
import numpy as np
abc = np.array([1, 2, 3, 4, 5, 6, 7])
filter_abc = abc % 2 == 0
newabc = abc[filter_abc]
print(filter_abc)
print(newabc)

[False  True False  True False  True False]
[2 4 6]
